### ISSUE TITLE
[Suggestion] Visibility

### ISSUE THREAD

**Issue by Clueless-AI** [lost-ark-dev/loa-details#13]
Hello, 
First of all I wanna thank everyone working and contributing to this wonderful tool, it helps a lot especially for a player like me coming for a WoW (Details) and FFXIV (ACT) background and who likes to optimize his gameplay.

As a 32 yo, my vision is kinda weak now and I was having a very difficult time reading the numbers or the texts displayed on the window because as we all know, we can make the window bigger but not the actual texts. So II was wondering if it is possible to add an option where we can make the default font bigger or completely change the font to a more readable one for people with difficulties like me just like the previously mentioned tools in the other two games (Details, ACT).

Thank you in advance.

**Comment by Mathicha** [comment]
ctrl+scroll to change font size

**Comment by Clueless-AI** [comment]
Oh, thank you so much that solves the issue. I really appreciate the help
