### ISSUE TITLE
Javascript error from nowhere

### ISSUE THREAD

**Issue by Pipole26** [lost-ark-dev/loa-details#19]
I'm guessing it's an issue on my end, but what gives? Already tried reinstalling it.

https://prnt.sc/CpsyV5U5g29E

Thanks

**Comment by Herysia** [comment]
Hey, you probably didn't install npcap, or if you did, try installing version 1.60 as mentioned in install instructions.
You can find npcap here: https://npcap.com/dist/npcap-1.60.exe

**Comment by Pipole26** [comment]
> Hey, you probably didn't install npcap, or if you did, try installing version 1.60 as mentioned in install instructions. You can find npcap here: https://npcap.com/dist/npcap-1.60.exe

Jesus christ... I actually uninstalled it like "wtf is that?" Completely forgot about it. Ty
