### ISSUE TITLE
have plan to create a dma version?

### ISSUE THREAD

**Issue by qhhuang** [lost-ark-dev/loa-details#34]
using npcap may be baned by smilegate.
may be use a dma device may safer than npcap?

**Comment by Herysia** [comment]
No.

I doubt that dma would be safer than passive packet sniffing as it would need to be an EAC bypass, which is a bad idea to make public.
If you want to opt for the super safe method, go for the 2PC method. Find a way to redirect/mirror your game pc packets to another machine running the meter.
